*;
*;
* HATCO - Multiple Regression Analysis;
*;
    ods graphics on;
*;
options ls=80 ps=50 nodate pageno=1;
ods all close;
ods pdf file = "E:\Multivariate Data Analysis BIA 652E\Assignments\Assignment 12 SAS_HATCO_MANOVA.pdf";
*;
*;
* Input HATCO ;
*;
Data HATCO;
Infile 'E:\Multivariate Data Analysis BIA 652E\Codes and Datasets\HATCO_X1-X14_Tabs.txt' DLM = '09'X TRUNCOVER;
Input X1 X2 X3 X4 X5 X6 X7 X8 X9 X10 X11 X12 X13 X14;
*;
Data HATCO;
	Set HATCO (Keep = X9 X10 X13 X14);
	Label X9 = 'X9 - Usage Level'
          X10 = 'X10 - Satisfaction Level'
          X13 = 'X13 - Type of Industry'
          X14 = 'X14 - Type of Buying Situation';
*;
Proc Print Data = HATCO;
Run;
*;
*;
* Exploratory Data Analysis - Univariate ;
*;
Proc Univariate Data = HATCO Normal Plot;
    Var X9 X10;
Run;
*;
Proc Sort Data = HATCO;
    By X14;
Run;
*;
Proc Univariate Data = HATCO Normal Plot;
    Var X9 X10;
	By X14;
	ID X14;
Run;
*;
*;
* GLM MANOVA Analysis - 3-Group Model;
*;
Proc GLM Data = HATCO;
    Class X14;
	Model X9 X10 = X14;
	Means X14 / Scheffe Tukey LSD SNK Duncan;
	Means X14 / Hovtest = Levene Hovtest = bf Hovtest = Bartlett;
	Means X14;
	Manova H = X14 / MStat = Exact;
Run;
*;
*;
* GLM MANOVA Analysis - Factorial Design Model;
*;
Proc GLM Data = HATCO;
    Class X14 X13;
	Model X9 X10 = X14 X13 X14*X13;
	Means X14 X13 X14*X13;
	Manova H = X14 X13 X14*X13 / MStat = Exact;
Run;
*;
*;
Run;
ods pdf close;
Quit;
